In [24]:
import pandas as pd

In [25]:
df = pd.read_csv('weather_data.csv', parse_dates=['day'])
df

         day  temperature  windspeed   event
0 2017-01-01         32.0        6.0    Rain
1 2017-01-04          NaN        9.0   Sunny
2 2017-01-05         28.0        NaN    Snow
3 2017-01-06          NaN        7.0     NaN
4 2017-01-07         32.0        NaN    Rain
5 2017-01-08          NaN        NaN   Sunny
6 2017-01-09          NaN        NaN     NaN
7 2017-01-10         34.1        8.1  Cloudy
8 2017-01-11         40.0       12.0   Sunny

In [26]:
type(df.day[0])

pandas._libs.tslibs.timestamps.Timestamp

In [27]:
df.set_index('day', inplace=True)
df

            temperature  windspeed   event
day
2017-01-01         32.0        6.0    Rain
2017-01-04          NaN        9.0   Sunny
2017-01-05         28.0        NaN    Snow
2017-01-06          NaN        7.0     NaN
2017-01-07         32.0        NaN    Rain
2017-01-08          NaN        NaN   Sunny
2017-01-09          NaN        NaN     NaN
2017-01-10         34.1        8.1  Cloudy
2017-01-11         40.0       12.0   Sunny

In [28]:
df.fillna(0)

            temperature  windspeed   event
day
2017-01-01         32.0        6.0    Rain
2017-01-04          0.0        9.0   Sunny
2017-01-05         28.0        0.0    Snow
2017-01-06          0.0        7.0       0
2017-01-07         32.0        0.0    Rain
2017-01-08          0.0        0.0   Sunny
2017-01-09          0.0        0.0       0
2017-01-10         34.1        8.1  Cloudy
2017-01-11         40.0       12.0   Sunny

In [35]:
df.fillna(method='bfill')

/tmp/ipython-input-2831856154.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method='bfill')

            temperature  windspeed   event
day
2017-01-01         32.0        6.0    Rain
2017-01-04         28.0        9.0   Sunny
2017-01-05         28.0        7.0    Snow
2017-01-06         32.0        7.0    Rain
2017-01-07         32.0        8.1    Rain
2017-01-08         34.1        8.1   Sunny
2017-01-09         34.1        8.1  Cloudy
2017-01-10         34.1        8.1  Cloudy
2017-01-11         40.0       12.0   Sunny

In [37]:
df.fillna(method='bfill', axis=1)

/tmp/ipython-input-1498511816.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method='bfill', axis=1)
/tmp/ipython-input-1498511816.py:1: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df.fillna(method='bfill', axis=1)

           temperature windspeed   event
day
2017-01-01        32.0       6.0    Rain
2017-01-04         9.0       9.0   Sunny
2017-01-05        28.0      Snow    Snow
2017-01-06         7.0       7.0     NaN
2017-01-07        32.0      Rain    Rain
2017-01-08       Sunny     Sunny   Sunny
2017-01-09         NaN       NaN     NaN
2017-01-10        34.1       8.1  Cloudy
2017-01-11        40.0      12.0   Sunny

In [38]:
df.interpolate()

/tmp/ipython-input-4002874584.py:1: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  df.interpolate()

            temperature  windspeed   event
day
2017-01-01         32.0      6.000    Rain
2017-01-04         30.0      9.000   Sunny
2017-01-05         28.0      8.000    Snow
2017-01-06         30.0      7.000     NaN
2017-01-07         32.0      7.275    Rain
2017-01-08         32.7      7.550   Sunny
2017-01-09         33.4      7.825     NaN
2017-01-10         34.1      8.100  Cloudy
2017-01-11         40.0     12.000   Sunny

In [40]:
df.dropna()

            temperature  windspeed   event
day
2017-01-01         32.0        6.0    Rain
2017-01-10         34.1        8.1  Cloudy
2017-01-11         40.0       12.0   Sunny

In [41]:
df

            temperature  windspeed   event
day
2017-01-01         32.0        6.0    Rain
2017-01-04          NaN        9.0   Sunny
2017-01-05         28.0        NaN    Snow
2017-01-06          NaN        7.0     NaN
2017-01-07         32.0        NaN    Rain
2017-01-08          NaN        NaN   Sunny
2017-01-09          NaN        NaN     NaN
2017-01-10         34.1        8.1  Cloudy
2017-01-11         40.0       12.0   Sunny

In [49]:
df.dropna(thresh=1)

            temperature  windspeed   event
day
2017-01-01         32.0        6.0    Rain
2017-01-04          NaN        9.0   Sunny
2017-01-05         28.0        NaN    Snow
2017-01-06          NaN        7.0     NaN
2017-01-07         32.0        NaN    Rain
2017-01-08          NaN        NaN   Sunny
2017-01-10         34.1        8.1  Cloudy
2017-01-11         40.0       12.0   Sunny