In [82]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv("weather_data.csv")
df

        day  temperature  windspeed     event
0  1/1/2017           32          6      Rain
1  1/2/2017       -99999          7     Sunny
2  1/3/2017           28     -99999      Snow
3  1/4/2017       -99999          7  no event
4  1/5/2017           32     -99999      Rain
5  1/6/2017           31          2     Sunny
6  1/6/2017           34     -88888  no event

In [84]:
df.replace([-99999, -88888], np.nan)

        day  temperature  windspeed     event
0  1/1/2017         32.0        6.0      Rain
1  1/2/2017          NaN        7.0     Sunny
2  1/3/2017         28.0        NaN      Snow
3  1/4/2017          NaN        7.0  no event
4  1/5/2017         32.0        NaN      Rain
5  1/6/2017         31.0        2.0     Sunny
6  1/6/2017         34.0        NaN  no event

In [85]:
df2 = pd.DataFrame({
    'name': ['Maria', 'Arjun', 'Alvin', 'Reena', 'Vishnu', 'Aleena'],
    'score': ['Excellent', 'Poor', 'Good', 'Average', 'Poor', 'Average']
})
df2

     name      score
0   Maria  Excellent
1   Arjun       Poor
2   Alvin       Good
3   Reena    Average
4  Vishnu       Poor
5  Aleena    Average

In [86]:
df2.replace(['Excellent', 'Poor', 'Good', 'Average'], [5, 2, 4, 3])

/tmp/ipython-input-3543562162.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df2.replace(['Excellent', 'Poor', 'Good', 'Average'], [5, 2, 4, 3])

     name  score
0   Maria      5
1   Arjun      2
2   Alvin      4
3   Reena      3
4  Vishnu      2
5  Aleena      3

SECTION 2

In [87]:
df3 = pd.read_csv('weather_by_cities.csv')
df3

         day      city  temperature  windspeed   event
0   1/1/2017  new york           32          6    Rain
1   1/2/2017  new york           36          7   Sunny
2   1/3/2017  new york           28         12    Snow
3   1/4/2017  new york           33          7   Sunny
4   1/1/2017    mumbai           90          5   Sunny
5   1/2/2017    mumbai           85         12     Fog
6   1/3/2017    mumbai           87         15     Fog
7   1/4/2017    mumbai           92          5    Rain
8   1/1/2017     paris           45         20   Sunny
9   1/2/2017     paris           50         13  Cloudy
10  1/3/2017     paris           54          8  Cloudy
11  1/4/2017     paris           42         10  Cloudy

In [88]:
g = df3.groupby('city')
g

In [89]:
g.get_group('mumbai')

        day    city  temperature  windspeed  event
4  1/1/2017  mumbai           90          5  Sunny
5  1/2/2017  mumbai           85         12    Fog
6  1/3/2017  mumbai           87         15    Fog
7  1/4/2017  mumbai           92          5   Rain

In [90]:
for city, data in g:
  print(f'City: {city}')
  print(f'Max. Temperature: {data.temperature.max()}')

City: mumbai
Max. Temperature: 92
City: new york
Max. Temperature: 36
City: paris
Max. Temperature: 54

In [91]:
g.min()

               day  temperature  windspeed   event
city
mumbai    1/1/2017           85          5     Fog
new york  1/1/2017           28          6    Rain
paris     1/1/2017           42          8  Cloudy

In [92]:
g.size()

city
mumbai      4
new york    4
paris       4
dtype: int64

In [93]:
g.describe()

         temperature                                                   \
               count   mean       std   min    25%   50%    75%   max
city
mumbai           4.0  88.50  3.109126  85.0  86.50  88.5  90.50  92.0
new york         4.0  32.25  3.304038  28.0  31.00  32.5  33.75  36.0
paris            4.0  47.75  5.315073  42.0  44.25  47.5  51.00  54.0

         windspeed
             count   mean       std  min   25%   50%    75%   max
city
mumbai         4.0   9.25  5.057997  5.0  5.00   8.5  12.75  15.0
new york       4.0   8.00  2.708013  6.0  6.75   7.0   8.25  12.0
paris          4.0  12.75  5.251984  8.0  9.50  11.5  14.75  20.0

Getting the group of data base on temperature ranges

In [94]:
def group_temp(df, idx, col):
  if 80 <= df.loc[idx, col] <= 90:
    return '80-90'
  elif 50 <= df.loc[idx, col] <= 60:
    return '50-60'
  else:
    return 'others'

In [95]:
g = df3.groupby(lambda idx: group_temp(df3, idx, 'temperature'))
for key, data in g:
  print(f'\nTemp b/w {key}:\n')
  print(data)

Temp b/w 50-60:

         day   city  temperature  windspeed   event
9   1/2/2017  paris           50         13  Cloudy
10  1/3/2017  paris           54          8  Cloudy

Temp b/w 80-90:

        day    city  temperature  windspeed  event
4  1/1/2017  mumbai           90          5  Sunny
5  1/2/2017  mumbai           85         12    Fog
6  1/3/2017  mumbai           87         15    Fog

Temp b/w others:

         day      city  temperature  windspeed   event
0   1/1/2017  new york           32          6    Rain
1   1/2/2017  new york           36          7   Sunny
2   1/3/2017  new york           28         12    Snow
3   1/4/2017  new york           33          7   Sunny
7   1/4/2017    mumbai           92          5    Rain
8   1/1/2017     paris           45         20   Sunny
11  1/4/2017     paris           42         10  Cloudy

Weather Data:

In [96]:
df4 = pd.DataFrame({
    'city': ['mumbai', 'delhi', 'banglore'],
    'temperature': [32, 45, 30],
    'humidity': [80, 60, 78]
})
df4

       city  temperature  humidity
0    mumbai           32        80
1     delhi           45        60
2  banglore           30        78

In [97]:
df5 = pd.DataFrame({
    'city': ['new york', 'chicago', 'orlando'],
    'temperature': [21, 14, 35],
    'humidity': [68, 65, 75]
})
df5

       city  temperature  humidity
0  new york           21        68
1   chicago           14        65
2   orlando           35        75

In [98]:
df6 = pd.concat([df4, df5], ignore_index=True)
df6

       city  temperature  humidity
0    mumbai           32        80
1     delhi           45        60
2  banglore           30        78
3  new york           21        68
4   chicago           14        65
5   orlando           35        75

In [99]:
pd.concat([df4, df5], keys=["India", "Us"])

             city  temperature  humidity
India 0    mumbai           32        80
      1     delhi           45        60
      2  banglore           30        78
Us    0  new york           21        68
      1   chicago           14        65
      2   orlando           35        75

In [100]:
df7 = pd.DataFrame({
    "city": ["Mumbai", "Kerala"],
    "temperature": [10, 15]
})
df7

     city  temperature
0  Mumbai           10
1  Kerala           15

In [101]:
df8 = pd.DataFrame({
    "city": ["Mumbai", "Kerala", "Delhi"],
    "windspeed": [34, 56, 20]
})
df8

     city  windspeed
0  Mumbai         34
1  Kerala         56
2   Delhi         20

In [102]:
pd.concat([df7, df8], axis=1)

     city  temperature    city  windspeed
0  Mumbai         10.0  Mumbai         34
1  Kerala         15.0  Kerala         56
2     NaN          NaN   Delhi         20

In [103]:
df9 = pd.DataFrame({
    "city": ["Mumbai", "Kerala", "Delhi"],
    "humidity": [40, 78, 54]
})
df9

     city  humidity
0  Mumbai        40
1  Kerala        78
2   Delhi        54

In [104]:
df10 = pd.merge(df8, df9, on='city')
df10

     city  windspeed  humidity
0  Mumbai         34        40
1  Kerala         56        78
2   Delhi         20        54